[project]
name = "pt-lightning-tutorial"
version = "0.1.0"
description = "A Simple Python demo that I used to learn about PyTorch lightning"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
